# Alacritty's config file.
# For more information, see https://alacritty.org/config-alacritty.html.

[shell]
program = "/usr/bin/zsh"

[window]
startup_mode = "Maximized"

option_as_alt = "OnlyLeft"

# To install a new font download the corresponding zip file and unzip it by
# running unzip path/to/zipped/font -d ~/.local/share/fonts/{font-name}, then
# run fc-cache -fv and ensure the font is correctly detected by the system
# by running fc-list | grep {font-name}.
[font]
normal      = { family = "Hasklug Nerd Font", style = "Medium"      }
italic      = { family = "Hasklug Nerd Font", style = "Italic"      }
bold        = { family = "Hasklug Nerd Font", style = "Bold"        }
bold_italic = { family = "Hasklug Nerd Font", style = "Bold Italic" }
size        = 14

# Kanagawa Alacritty Colors
[colors.primary]
background = "0x1f1f28"
foreground = "0xdcd7ba"

[colors.normal]
black = "0x090618"
red = "0xc34043"
green = "0x76946a"
yellow = "0xc0a36e"
blue = "0x7e9cd8"
magenta = "0x957fb8"
cyan = "0x6a9589"
white = "0xc8c093"

[colors.bright]
black = "0x727169"
red = "0xe82424"
green = "0x98bb6c"
yellow = "0xe6c384"
blue = "0x7fb4ca"
magenta = "0x938aa9"
cyan = "0x7aa89f"
white = "0xdcd7ba"

[colors.selection]
background = "0x2d4f67"
foreground = "0xc8c093"

[[colors.indexed_colors]]
index = 16
color = "0xffa066"

[[colors.indexed_colors]]
index = 17
color = "0xff5d62"

